curl 'https://zkluwfclukbwnsitvntv.supabase.co/rest/v1/cabins?select=*' \
-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprbHV3ZmNsdWtid25zaXR2bnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMjg1OTcsImV4cCI6MjA1NTcwNDU5N30.xJ0w8W0MDBmXMmBKVHJcooVEHPbTy_hRDubX0iuUpEU" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprbHV3ZmNsdWtid25zaXR2bnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMjg1OTcsImV4cCI6MjA1NTcwNDU5N30.xJ0w8W0MDBmXMmBKVHJcooVEHPbTy_hRDubX0iuUpEU"



curl 'https://zkluwfclukbwnsitvntv.supabase.co/rest/v1/settings?select=*' \
-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprbHV3ZmNsdWtid25zaXR2bnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMjg1OTcsImV4cCI6MjA1NTcwNDU5N30.xJ0w8W0MDBmXMmBKVHJcooVEHPbTy_hRDubX0iuUpEU" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprbHV3ZmNsdWtid25zaXR2bnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMjg1OTcsImV4cCI6MjA1NTcwNDU5N30.xJ0w8W0MDBmXMmBKVHJcooVEHPbTy_hRDubX0iuUpEU"
